version: '3.5'
services:
  # The Application
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      #- entanet-shared
      - frontend
      - backend
    depends_on:
      - database
    environment:
      - "APP_NAME=app"
      - "APP_URL=http://localhost:8080"
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_HOST=database"
      - "DB_PASSWORD=secret"

  # NGINX
  web:
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    working_dir: /var/www
    networks:
      - frontend
    depends_on:
      - app
    volumes:
      - ./public:/var/www/public
    ports:
      - 8080:80

  # The database
  database:
    build:
      context: ./
      dockerfile: docker/database/Dockerfile
    networks:
      - backend
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"

networks:
  #entanet-shared:
  #external: true
  frontend:
  backend: